//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class bookTable
    {
        public int accessno { get; set; }
        public string bookname { get; set; }
        public string author { get; set; }
        public string publication { get; set; }
        public string bookcategory { get; set; }
        public string place { get; set; }
        public string condition { get; set; }
        public int copies { get; set; }
    }
}
