//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class guestTable
    {
        public int guestid { get; set; }
        public string guestname { get; set; }
        public string guestintial { get; set; }
        public string guestintroducedby { get; set; }
        public string guestaddress { get; set; }
    }
}
