//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class guestissueTable
    {
        public int guestid { get; set; }
        public int accessno { get; set; }
        public string guestname { get; set; }
        public string introducedby { get; set; }
        public string address { get; set; }
        public string bookname { get; set; }
        public System.DateTime issuedate { get; set; }
    }
}
