//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MylibEntities2 : DbContext
    {
        public MylibEntities2()
            : base("name=MylibEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<bookTable> bookTables { get; set; }
        public DbSet<guestTable> guestTables { get; set; }
        public DbSet<loginTable> loginTables { get; set; }
        public DbSet<staffTable> staffTables { get; set; }
        public DbSet<stdTable> stdTables { get; set; }
        public DbSet<guestissuecopyTable> guestissuecopyTables { get; set; }
        public DbSet<guestissueTable> guestissueTables { get; set; }
        public DbSet<guestreturnTable> guestreturnTables { get; set; }
        public DbSet<staffissuecopyTable> staffissuecopyTables { get; set; }
        public DbSet<staffissueTable> staffissueTables { get; set; }
        public DbSet<staffreturnTable> staffreturnTables { get; set; }
        public DbSet<stdissuecopyTable> stdissuecopyTables { get; set; }
        public DbSet<stdissueTable> stdissueTables { get; set; }
        public DbSet<stdreturnTable> stdreturnTables { get; set; }
    }
}
