//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class staffTable
    {
        public int staffid { get; set; }
        public string staffname { get; set; }
        public string staffintial { get; set; }
        public string staffdepartment { get; set; }
    }
}
