//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class stdreturnTable
    {
        public int accessno { get; set; }
        public int stdrollno { get; set; }
        public string stdname { get; set; }
        public string stdclass { get; set; }
        public int stdyear { get; set; }
        public string bookname { get; set; }
        public System.DateTime issuedate { get; set; }
        public System.DateTime returndate { get; set; }
    }
}
